export default {
   user:{
      id: null,
      fullName: '',
      dateOfBirth: '',
      email: '',
      phone : '',
      address : '',
      gender : '',
      avatar : ''
   },  
   isLogin : false,
   isAdmin : false,
   isLoading: false,
   // email: '',
   images: [],
   products: [],
   auction:[],
   filterProducts: [],
   productDetail: {
      id: '',
      name: '',
      category: '',
      description: '',
      images: '',
      owner: '',
   },
   sessions: [],
   filterAuctions: [],
};